---
- name: Check and install package updates
  hosts: all
  become: true
  pre_tasks:
    - name: Update repo cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

- hosts: all
  become: true
  roles:
    - docker_hosts
    - users
