---
- name: Initial setups for VPS
  hosts: all
  become: true
  tasks:
    - name: Install Packages
      ansible.builtin.apt:
        name:
          - zsh
          - git
          - curl
        state: present
        update_cache: true

- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - curl
          - ca-certificates
          - gnupg
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker CE
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

- name: Create users
  hosts: all
  become: true
  tasks:
    - name: 'Create user jasonj, and add him to groups: `sudo`, `docker`'
      ansible.builtin.user:
        name: jasonj
        shell: /usr/bin/zsh
        groups: sudo, docker
        append: true
        create_home: true

    - name: Add SSH key for jasonj
      ansible.builtin.authorized_key:
        user: jasonj
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDITvPZPoipKNmOdBbbXO7gL7yYnlBHT805EWjk7mmaGhMde+UFw1kItUGUx2hCo6BAIcLp/yK+DyErSFwWlhSK51TYFAVVmMwPEhirMwQgvGshS10vGVXxeCevNbQAd65UGijM/JIdXqWDm8wsH8QGJbMNCDs9IGisbhjo7kSQYirYmcoxjV+oA/0QTaS9Jek7SRueWdQxjbcAbEVjt15MxpjeNr1I7F05/LpWAURxMFpbBBHVLfBEpG41mUbVqds4xXPSS5U6ygCkHZ45pIwRgRS1GrYaTClcsibKG97uUANPNq98GY8LcsSJibzm5rUh2KwjWTWPTs5jQq17LQlv jjpro default" # noqa
        state: present

    - name: Add sudoers file for jasonj, so he can sudo without password 
      ansible.builtin.copy:
        src: sudoer_jasonj
        dest: /etc/sudoers.d/jasonj
        owner: root
        group: root
        mode: 440

    - name: Check if Oh My Zsh is installed for jasonj
      ansible.builtin.stat:
        path: /home/jasonj/.oh-my-zsh
      register: omz_status

    - name: Install Oh My Zsh for jasonj
      ansible.builtin.shell: yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      become_user: jasonj
      when: omz_status.stat.exists == false
