---
- name: Check and install package updates
  hosts: all
  become: true
  tasks:
    - name: Update repo cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - curl
          - ca-certificates
          - gnupg
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker CE
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

- name: Create users
  hosts: all
  become: true
  tasks:
    - name: 'Create user jasonj, and add him to groups: `sudo`, `docker`'
      ansible.builtin.user:
        name: jasonj
        shell: /usr/bin/zsh
        groups: sudo, docker
        append: true
        create_home: true

    - name: Add SSH key for jasonj
      ansible.builtin.authorized_key:
        user: jasonj
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: Add sudoers file for jasonj, so he can sudo without password
      ansible.builtin.copy:
        src: sudoer_jasonj
        dest: /etc/sudoers.d/jasonj
        owner: root
        group: root
        mode: 440

    - name: Check if Oh My Zsh is installed for jasonj
      ansible.builtin.stat:
        path: /home/jasonj/.oh-my-zsh
      register: omz_status

    - name: Install Oh My Zsh for jasonj
      ansible.builtin.shell: yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      become_user: jasonj
      when: omz_status.stat.exists == false
